### ISSUE TITLE
Deprecation warning fix for serverless 3.0.0

### ISSUE THREAD

**Issue by gghukasyan** [AntonBazhal/serverless-plugin-custom-roles#18] opened 2021-06-25 10:39 UTC
Right now with serverless 2 we're getting the following warning
Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
Plugin needs to add support for provider.iam.role.statements

**Comment by AntonBazhal** [comment] 2021-06-25 14:16
Duplicate of #16

**Closed by AntonBazhal** 2021-06-25 14:16 UTC
