### ISSUE TITLE
Reference Roles

### ISSUE THREAD

**Issue by Infabytes-DavidChannon** [AntonBazhal/serverless-plugin-custom-roles#10] opened 2019-10-15 12:24 UTC
Hi,

How can I reference the role generated for a lambda function, I need the ARN for a specific role?

Use case is that I have an AWS::Elasticsearch::Domain in the resources section of serverless.yml.
That has an AccessPolicy Statement in which I need to add the Role ARN's as the principals.
I can't wildcard the role ARN as you can't wildcard in principals.
I also can't generate the ARN with join or anything as the role ARN's have a 12 character random string on the end.

Thanks

**Comment by AntonBazhal** [comment] 2019-10-15 15:18
Hey, the role resource follows the name convention of `<function name>LambdaFunctionRole`, like if you have a function called `foo`, the role name is gonna be `FooLambdaFunctionRole`. You can use `Fn::GetAtt` to get ARN based on the resource name. Let me know if this worked for you.

**Comment by Infabytes-DavidChannon** [comment] 2019-10-16 17:54
I think in principal it works.
However I have run into a circular dependency issue.

The ElasticSearch domain endpoint is set as an environment variable:

`provider:
  name: aws
  environment:
    ESDOMAINENDPOINT: !GetAtt ElasticSearchDomain.DomainEndpoint `

So that is then passed into the functions.

That means though that the generated CF nested template for the function then contains that parameter.
The same nested template also contains the "*LambdaFunctionRole"

The ElasticSearch resource ( which ends up in the main CF template ) is then referencing the the LambdaFunctionRole.

I  think that is what is going on.

Trying to figure out the best way around it.

**Comment by AntonBazhal** [comment] 2019-10-16 19:11
Hmm. Do you have per-function nested stacks?

**Comment by Infabytes-DavidChannon** [comment] 2019-10-16 20:57
Yup.
To many resources otherwise.

I managed to resolve it.

I changed the Environment Variable to an SSM Parameter.
Created the SSM Paramater as a resource using the get att for ElasticSearch domain name.

It all now works.
Just need to check it works when launching a fully new stack but think it will.

**Comment by AntonBazhal** [comment] 2019-10-16 21:06
Cool. Per-function stack is a nice way to avoid hitting CF stack size limit. The other option would be to split by resource type (which would help to avoid circular dependency in your case), but it's another can of worms and impossible to do on something that's been deployed already.

**Comment by Infabytes-DavidChannon** [comment] 2019-10-16 21:34
Yeah - I think I initially tried split by resource type but it did not resolve the stack size limit issue - not sure though.

Thanks!!!

**Comment by AntonBazhal** [comment] 2019-10-17 15:05
[serverless-plugin-split-stacks](https://www.npmjs.com/package/serverless-plugin-split-stacks) is a great help for the stack size problem. Closing as I assume the issue is resolved.

**Closed by AntonBazhal** 2019-10-17 15:05 UTC
